### ISSUE TITLE
Using the Balabit Mouse Challenge Data Set

### ISSUE THREAD

**Issue by a-posadas** [avinabsaha/Biometric-Authentication-Using-Mouse-Dynamics#1]
I converted the Balabit Mouse Challenge data set to the format described in the pdf but my results look different:
```
Training accuracy:
78.00841514726508
Test accuracy:
18.294918805657414
Precision:
0.021711680998017603
Recall:
0.7717684021543986
F1 Score:
0.04223518575376114
```
I chose the Balabit data set because it looks like there is no data set in this github. Is it possible to use any mouse dynamic data so long as it is correctly formatted or do the scripts only work for a specific arrangement of tasks and computers. 

Or is it simply a lack of data. I had to modify your script a bit because the Balabit data set only has ten users while you seem to have had 15. 

Also, the Balabit only has about 6 or 7 sessions per user, you have a lot more. I don't even know how long the sessions are. The Balabit sessions are a few hours long. I'm sure all this sort of matters I suppose. 

Or something else. I don't know because I'm new to machine learning so a lot of this stuff is over my head. But I did study some statistics in college. 

Thanks in advance

**Comment by avinabsaha** [comment]
I feel you might need to tune hyper parameters according to the data you
are using. That might give better results.

Also, the code uses one class SVM which I feel isn't a very good method.
You might use other machine learning models for better results.

Cheers!

Avinab Saha

**Comment by a-posadas** [comment]
Thank you for the prompt response. I was wondering, what other machine learning models do you suggest and are there python implementations?

**Comment by avinabsaha** [comment]
Hey,

You might use Machine Learning models like Neural Networks, SVMs, etc. You
might want to look at the Sklearn library for implementation of the machine
learning models.

**Comment by a-posadas** [comment]
ok, sounds good. I will give it a try. Thanks a bunch! If I have any other questions, would you mind too terribly if I contacted you again? Do you have an email I could send to? It's ok if you're busy, I'll understand.

**Comment by Saif-Haider** [comment]
How can one create the data (which are store in the .txt file of different user)?

**Comment by avinabsaha** [comment]
Hi Saif,

I did this project as a part of one of my term projects back in college. To collect data, our professor had given a tool to collect and annotate data. I am sorry but I don't have the software now.
